local c = require('tsuki.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- highlights
  hl(0, "Normal", { fg = c._l_white, bg = c._black, })
  hl(0, "NormalNC", { fg = c._l_white, bg = c._black, })
  hl(0, "NormalSB", { fg = c._d_white, bg = c._semiblack, })
  hl(0, "NormalFloat", { fg = c._l_white, bg = c._black, })
  hl(0, "FloatBorder", { fg = c._lightblack, bg = 'NONE', })
  hl(0, "Darker", { fg = c._gray, bg = c._black, })
  hl(0, "ColorColumn", { fg = c._black, bg = c._l_pink, })
  hl(0, "Conceal", { fg = c._yellow, bg = 'NONE', bold=true, })
  hl(0, "Cursor", { fg = c._black, bg = c._l_pink, })
  hl(0, "iCursor", { fg = c._black, bg = c._earth, })
  hl(0, "CursorLine", { fg = 'NONE', bg = c._semiblack, })
  hl(0, "CursorLineNr", { fg = c._gray_dark, bg = c._semiblack, })
  hl(0, "Directory", { fg = c._earth, bg = c._black, })
  hl(0, "ErrorMsg", { fg = c._black, bg = c._l_pink, })
  hl(0, "FoldColumn", { fg = 'NONE', bg = c._black, })
  hl(0, "Folded", { fg = c._l_white, bg = c._semiblack, })
  hl(0, "LineNr", { fg = c._lightblack, bg = c._black, })
  hl(0, "MatchParen", { fg = c._black, bg = c._l_white, })
  hl(0, "ModeMsg", { fg = c._black, bg = c._earth, })
  hl(0, "Whitespace", { fg = c._semiblack, bg = 'NONE', })
  hl(0, "Pmenu", { fg = c._l_white, bg = c._semiblack, })
  hl(0, "PmenuSel", { fg = 'NONE', bg = c._gray_dark, })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = c._black, })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c._black, })
  hl(0, "Search", { fg = 'NONE', bg = c._gray_dark, underline=true, })
  hl(0, "SignColumn", { fg = 'NONE', bg = c._black, })
  hl(0, "StatusLine", { fg = c._gray, bg = c._semiblack, })
  hl(0, "StatusLineNC", { fg = c._gray_dark, bg = c._semiblack, })
  hl(0, "Tabline", { fg = c._gray, bg = 'NONE', })
  hl(0, "TablineFill", { fg = 'NONE', bg = c._black, })
  hl(0, "TabLineSel", { fg = c._l_sky, bg = c._black, reverse=true, })
  hl(0, "Title", { fg = c._earth, bg = 'NONE', bold=true, })
  hl(0, "Todo", { fg = c._black, bg = c._sky, italic=true, })
  hl(0, "VertSplit", { fg = c._lightblack, bg = 'NONE', })
  hl(0, "Visual", { fg = 'NONE', bg = c._lightblack, })
  hl(0, "WarningMsg", { fg = c._pink, bg = c._black, })
  hl(0, "Access", { fg = c._earth, bg = 'NONE', bold=true, })
  hl(0, "Character", { fg = c._sky, bg = 'NONE', })
  hl(0, "Define", { fg = c._gray_light, bg = 'NONE', })
  hl(0, "Function", { fg = c._d_turquoise, bg = 'NONE', })
  hl(0, "Label", { fg = c._d_turquoise, bg = 'NONE', })
  hl(0, "Module", { fg = c._l_pink, bg = 'NONE', underline=true, })
  hl(0, "NonText", { fg = c._gray_dark, bg = 'NONE', })
  hl(0, "String", { fg = c._earth, bg = 'NONE', })
  hl(0, "Structure", { fg = c._gray, bg = 'NONE', })
  hl(0, "Object", { fg = c._gray, bg = 'NONE', })
  hl(0, "Xml", { fg = c._purple, bg = 'NONE', })
  hl(0, "Punctuation", { fg = c._purple, bg = 'NONE', })
  hl(0, "Attr", { fg = c._green, bg = 'NONE', })
  hl(0, "Comment", { fg = c._gray_light, bg = 'NONE', })
  hl(0, "Constant", { fg = c._earth, bg = 'NONE', bold=true, })
  hl(0, "Identifier", { fg = c._l_pink, bg = 'NONE', })
  hl(0, "Statement", { fg = c._l_sky, bg = 'NONE', })
  hl(0, "PreProc", { fg = c._white, bg = 'NONE', })
  hl(0, "Type", { fg = c._d_white, bg = 'NONE', })
  hl(0, "Special", { fg = c._l_pink, bg = 'NONE', })
  hl(0, "Underlined", { fg = c._earth, bg = 'NONE', underline=true, })
  hl(0, "Error", { fg = c._black, bg = c._l_pink, })
  hl(0, "MarkdownH1", { fg = c._sky, bg = 'NONE', bold=true, })
  hl(0, "MarkdownH2", { fg = c._l_sky, bg = 'NONE', bold=true, })
  hl(0, "MarkdownLinkText", { fg = c._l_sky, bg = 'NONE', underline=true, })
  hl(0, "UnderlinedBold", { fg = c._earth, bg = 'NONE', underline=true, bold=true, })
  hl(0, "DiffAdd", { fg = c._green, bg = c._black, })
  hl(0, "DiffChange", { fg = c._white, bg = c._black, })
  hl(0, "DiffDelete", { fg = c._pink, bg = c._black, })
  hl(0, "DiffText", { fg = c._pink, bg = c._black, })
  hl(0, "Boolean", { link = 'Number' })
  hl(0, "Class", { link = 'Constant' })
  hl(0, "Delimiter", { link = 'Define' })
  hl(0, "Debug", { link = 'Special' })
  hl(0, "Conditional", { link = 'Define' })
  hl(0, "Exception", { link = 'PreProc' })
  hl(0, "Float", { link = 'Number' })
  hl(0, "Include", { link = 'PreProc' })
  hl(0, "Macro", { link = 'PreProc' })
  hl(0, "Number", { link = 'Identifier' })
  hl(0, "Operator", { link = 'Identifier' })
  hl(0, "PreCondit", { link = 'PreProc' })
  hl(0, "Repeat", { link = 'Statement' })
  hl(0, "SpecialChar", { link = 'Special' })
  hl(0, "SpecialComment", { link = 'Special' })
  hl(0, "SpecialKey", { link = 'Define' })
  hl(0, "StorageClass", { link = 'Identifier' })
  hl(0, "Symbol", { link = 'PreProc' })
  hl(0, "Tag", { link = 'Number' })
  hl(0, "Typedef", { link = 'Type' })

end

return theme